import Link from "next/link";
import { getCategories, getSubcategories, getBusinesses } from "@/lib/data";
import BusinessCard from "@/components/BusinessCard";
export default async function SubcategoryPage({ params }: { params: Promise<{ slug: string; sub: string }> }) {
  const { slug, sub } = await params;
  const [categories, subcategories, businesses] = await Promise.all([getCategories(), getSubcategories(slug), getBusinesses({ categorySlug: slug, subcategorySlug: sub })]);
  const category = categories.find((item) => item.slug === slug); const selected = subcategories.find((item) => item.slug === sub);
  return <div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><Link href={'/category/' + slug} className="text-sm font-bold text-[#8a7b79] transition hover:text-[#c91442]">← بازگشت به {category?.name || "دسته"}</Link><div className="mt-7 flex flex-col justify-between gap-5 rounded-[2rem] border border-[#eadfd7] bg-white p-6 sm:flex-row sm:items-end sm:p-9"><div><p className="text-xs font-black tracking-[0.22em] text-[#c91442]">LOCAL DISCOVERY</p><h1 className="mt-3 text-3xl font-black text-[#241b1c]">{selected?.name || "کسب‌وکارهای محلی"}</h1><p className="mt-2 text-sm text-[#80716f]">نتیجه‌های نزدیک و مرتبط، بدون رتبه‌بندی پولی.</p></div><span className="rounded-full bg-[#fff7f2] px-4 py-2 text-sm font-black text-[#c91442]">{businesses.length} نتیجه</span></div><div className="mt-7 flex flex-wrap gap-2">{subcategories.map((item) => <Link key={item.id} href={'/category/' + slug + '/' + item.slug} className={'rounded-full border px-3 py-2 text-xs font-bold transition ' + (item.slug === sub ? 'border-[#c91442] bg-[#c91442] text-white' : 'border-[#eadfd7] bg-white text-[#665655] hover:border-[#c91442]/40 hover:text-[#c91442]')}>{item.name}</Link>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{businesses.map((b) => <BusinessCard key={b.id} b={b} />)}{businesses.length === 0 && <div className="col-span-full rounded-3xl border border-dashed border-[#d8c8c2] bg-[#fffaf7] py-16 text-center"><p className="font-black text-[#3b2d2e]">هنوز نتیجه‌ای برای این تخصص ثبت نشده.</p><Link href="/register-business" className="mt-4 inline-flex rounded-full bg-[#c91442] px-5 py-2.5 text-sm font-bold text-white">ثبت این کسب‌وکار</Link></div>}</div></div>;
}
