import Link from "next/link";
import CategoryExplorer from "@/components/CategoryExplorer";
import { getDirectory } from "@/lib/data";

export default async function Home() {
  const { categories, subcategories } = await getDirectory();
  return <div className="min-h-screen bg-[#fffdf9]">
    <section className="relative overflow-hidden border-b border-[#eadfd7] bg-white"><div className="pointer-events-none absolute -left-32 top-4 h-96 w-96 rounded-full bg-[#e86b91]/10 blur-3xl" /><div className="pointer-events-none absolute -right-28 bottom-0 h-[32rem] w-[32rem] rounded-full bg-[#f4c95d]/20 blur-3xl" /><div className="mx-auto grid max-w-7xl gap-10 px-5 pb-14 pt-10 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:px-8 lg:pb-20 lg:pt-16">
      <div className="relative order-2 text-right lg:order-1"><span className="inline-flex items-center gap-2 rounded-full border border-[#c91442]/15 bg-[#c91442]/[0.06] px-4 py-2 text-xs font-black text-[#a70f37]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#c91442]" /> دایرکتوری واقعی شهر تو</span><h1 className="mt-6 max-w-2xl text-4xl font-black leading-[1.35] text-[#241b1c] sm:text-6xl">هر چیزی که می‌خوای،<span className="block text-[#c91442]">همین نزدیکی‌هاست.</span></h1><p className="mt-5 max-w-xl text-base leading-8 text-[#6f6261] sm:text-lg">بیرون، کسب‌وکارهای واقعی شهر را از کافه و طلافروشی تا دیجیتال مارکتینگ و آموزش، با دسته‌بندی دقیق کنار هم می‌آورد.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="#categories" className="rounded-2xl bg-[#c91442] px-6 py-3.5 text-sm font-black text-white shadow-[0_12px_25px_-14px_rgba(201,20,66,0.9)] transition hover:-translate-y-0.5 hover:bg-[#a70f37]">شروع جست‌وجو</Link><Link href="/register-business" className="rounded-2xl border border-[#eadfd7] bg-white px-6 py-3.5 text-sm font-black text-[#5f4b4b] transition hover:border-[#c91442]/40 hover:text-[#c91442]">ثبت کسب‌وکار</Link><Link href="/register-online-shop" className="rounded-2xl border border-[#cfe6df] bg-[#f1fbf7] px-6 py-3.5 text-sm font-black text-[#287c68] transition hover:border-[#287c68]/50">ثبت آنلاین‌شاپ</Link></div><div className="mt-7 flex flex-wrap gap-2 text-xs text-[#8a7b79]"><span className="rounded-full bg-[#fff7f2] px-3 py-2 font-bold">📍 مشهد، شروع ماجرا</span><span className="rounded-full bg-[#fff7f2] px-3 py-2 font-bold">⚡ پیدا کردن در چند ثانیه</span><span className="rounded-full bg-[#fff7f2] px-3 py-2 font-bold">⚖️ دیده‌شدن عادلانه</span></div></div>
      <div className="relative order-1 min-h-[300px] lg:order-2 lg:min-h-[450px]"><div className="absolute inset-x-4 top-5 bottom-0 rounded-[3rem] bg-gradient-to-br from-[#fff4e8] via-[#fff9f4] to-[#f9e4e9] shadow-[0_35px_90px_-35px_rgba(110,43,45,0.4)]" /><div className="absolute right-7 top-8 rotate-6 rounded-2xl border border-white bg-white/90 px-4 py-3 text-xs font-black text-[#c91442] shadow-lg">همه دیده می‌شوند ✦</div><div className="absolute left-8 top-20 -rotate-6 rounded-2xl border border-white bg-white/90 px-4 py-3 text-xs font-black text-[#42796f] shadow-lg">نزدیک‌ترین‌ها اینجاست</div><div className="absolute inset-0 grid place-items-center"><div className="grid h-56 w-56 place-items-center rounded-[2.75rem] border-8 border-white bg-[#fffaf0] shadow-[0_20px_60px_-25px_rgba(191,141,46,0.6)] sm:h-72 sm:w-72"><img src="/beeroon-logo-final.png?v=3" alt="لوگوی بیرون" className="h-4/5 w-4/5 object-contain" /></div></div><div className="absolute bottom-4 right-5 rounded-2xl border border-[#eadfd7] bg-white px-4 py-3 shadow-lg"><p className="text-[11px] text-[#8a7b79]">امروز در بیرون</p><p className="mt-1 text-sm font-black text-[#3b2d2e]">{categories.length} دسته · {subcategories.length}+ تخصص</p></div></div>
    </div></section>
    <CategoryExplorer categories={categories} subcategories={subcategories} />
    <section className="border-y border-[#eadfd7] bg-[#fff7f2]"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-12 sm:grid-cols-3 lg:px-8">{[["۰۱","پیدا کن","از دسته اصلی تا ریزترین خدمت، بدون سرنخ‌های گمراه‌کننده."],["۰۲","مقایسه کن","تلفن، آدرس، ساعت کاری و شبکه‌های اجتماعی یک‌جا."],["۰۳","بیرون بزن","کسب‌وکار نزدیکت را پیدا کن و مستقیم با خودش ارتباط بگیر."]].map(([number,title,description]) => <div key={number} className="flex gap-4"><span className="text-sm font-black text-[#c91442]">{number}</span><div><h3 className="font-black text-[#3b2d2e]">{title}</h3><p className="mt-1 text-sm leading-7 text-[#80716f]">{description}</p></div></div>)}</div></section>
    <section className="mx-auto max-w-5xl px-5 py-14 text-center lg:py-20"><p className="text-xs font-black tracking-[0.25em] text-[#c91442]">FOR LOCAL OWNERS</p><h2 className="mt-3 text-3xl font-black text-[#241b1c]">کسب‌وکار داری؟ دیده شو.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-7 text-[#80716f]">پروفایل کاملت را ثبت کن تا مشتری‌ها آدرس، تلفن و شبکه‌های اجتماعی‌ات را یک‌جا پیدا کنند.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href="/register-business" className="inline-flex rounded-full bg-[#c91442] px-7 py-3.5 font-bold text-white transition hover:bg-[#a70f37]">ثبت رایگان کسب‌وکار</Link><Link href="/register-online-shop" className="inline-flex rounded-full border border-[#287c68]/25 bg-[#f1fbf7] px-7 py-3.5 font-bold text-[#287c68] transition hover:bg-[#e1f5ee]">ثبت آنلاین‌شاپ</Link></div></section>
  </div>;
}
