import Link from "next/link";
import { Business } from "@/lib/types";

const priceLabel = { 1: "اقتصادی", 2: "متوسط", 3: "ویژه" } as const;

function SocialLink({ href, label, tone = "neutral" }: { href: string; label: string; tone?: "neutral" | "red" | "gold" | "blue" }) {
  const tones = { neutral: "border-[#eadfe2] text-[#5e4a52] hover:border-[#ef4056] hover:text-[#ef4056]", red: "border-[#f5c4cb] bg-[#fff5f6] text-[#d9364b] hover:bg-[#ffecef]", gold: "border-[#ead9a9] bg-[#fffaf0] text-[#8f6d22] hover:bg-[#f8f0da]", blue: "border-[#cedeea] bg-[#f4f9fc] text-[#2c668f] hover:bg-[#e6f2fa]" };
  return <a href={href} target="_blank" rel="noreferrer" className={"inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-[10px] font-bold transition " + tones[tone]}>{label}</a>;
}

export default function BusinessCard({ b }: { b: Business }) {
  const onlineShop = Array.isArray(b.online_shop_details) ? b.online_shop_details[0] : b.online_shop_details;
  const websiteUrl = onlineShop?.website_url;
  const instagramUrl = b.instagram?.startsWith("http") ? b.instagram : b.instagram ? "https://instagram.com/" + b.instagram.replace(/^@/, "") : null;
  const mapUrl = b.neshan ? (b.neshan.startsWith("http") ? b.neshan : "https://neshan.org/maps/search/" + encodeURIComponent(b.neshan)) : b.lat && b.lng ? "https://neshan.org/maps/@" + b.lat + "," + b.lng + ",16z" : null;
  return <article className="card-hover group relative overflow-hidden rounded-[1.45rem] border border-[#f0dfe3] bg-white p-4 shadow-[0_10px_28px_-24px_rgba(111,35,50,.6)]"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-[#ffd36e] via-[#ef4056] to-[#a94574]" /><div className="flex items-start gap-3 pt-1"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-[#ffdce4] to-[#fff3d8] text-xl text-[#ef4056] shadow-[0_8px_16px_-12px_rgba(239,64,86,.7)]">✦</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><h3 className="truncate text-sm font-black text-[#33212b]"><Link href={"/business/" + b.id} className="transition hover:text-[#ef4056]">{b.name}</Link></h3>{b.business_type === "online_shop" && <span className="rounded-md bg-[#ecfdf5] px-1.5 py-1 text-[9px] font-bold text-[#16805f]">آنلاین</span>}{b.is_supporter && <span className="rounded-md bg-[#fff8e1] px-1.5 py-1 text-[9px] font-bold text-[#9a6b00]">ویژه</span>}</div>{b.address && <p className="mt-1 truncate text-[11px] text-[#87737b]">{b.address}</p>}</div></div><div className="mt-4 flex items-center gap-2 border-t border-[#f6edef] pt-3 text-[10px] text-[#87737b]">{b.price_tier && <span className="rounded-md bg-[#fff8e5] px-2 py-1 font-bold text-[#9a7525]">{priceLabel[b.price_tier]}</span>}{b.hours && <span className="truncate">• {b.hours}</span>}</div><div className="mt-3 flex flex-wrap gap-1.5">{b.phone && <SocialLink href={"tel:" + b.phone} label="تماس" tone="red" />}{instagramUrl && <SocialLink href={instagramUrl} label="اینستاگرام" tone="red" />}{websiteUrl && <SocialLink href={websiteUrl} label="سایت" tone="gold" />}{b.telegram && <SocialLink href={"https://t.me/" + b.telegram} label="تلگرام" tone="blue" />}{b.whatsapp && <SocialLink href={"https://wa.me/" + b.whatsapp} label="واتساپ" tone="gold" />}{mapUrl && <SocialLink href={mapUrl} label="مسیریابی" tone="neutral" />}</div><Link href={"/business/" + b.id} className="mt-4 inline-flex text-[10px] font-black text-[#ef4056] transition hover:text-[#d9364b]">دیدن جزئیات و همه راه‌های ارتباطی ←</Link></article>;
}
