"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Category, Subcategory } from "@/lib/types";

type Props = { categories: Category[]; subcategories: Subcategory[] };
const visuals: Record<string, { glyph: string; tone: string }> = {
  food: { glyph: "🍽️", tone: "from-orange-100 to-amber-50 text-orange-700" }, shopping: { glyph: "🛍️", tone: "from-pink-100 to-rose-50 text-rose-700" }, fashion: { glyph: "👗", tone: "from-fuchsia-100 to-purple-50 text-fuchsia-700" }, beauty: { glyph: "💄", tone: "from-rose-100 to-pink-50 text-rose-700" }, health: { glyph: "🩺", tone: "from-cyan-100 to-sky-50 text-cyan-700" }, education: { glyph: "🎓", tone: "from-blue-100 to-indigo-50 text-blue-700" }, home: { glyph: "🛋️", tone: "from-yellow-100 to-orange-50 text-amber-700" }, automotive: { glyph: "🚗", tone: "from-slate-200 to-sky-50 text-slate-700" }, travel: { glyph: "✈️", tone: "from-sky-100 to-cyan-50 text-sky-700" }, sport: { glyph: "🏃", tone: "from-green-100 to-emerald-50 text-emerald-700" }, culture: { glyph: "🎨", tone: "from-violet-100 to-fuchsia-50 text-violet-700" }, technical: { glyph: "🔧", tone: "from-stone-200 to-amber-50 text-stone-700" }, business: { glyph: "📣", tone: "from-red-100 to-orange-50 text-red-700" }, technology: { glyph: "💻", tone: "from-indigo-100 to-blue-50 text-indigo-700" }, finance: { glyph: "💳", tone: "from-emerald-100 to-teal-50 text-emerald-700" }, legal: { glyph: "⚖️", tone: "from-gray-200 to-slate-50 text-slate-700" }, "real-estate": { glyph: "🏠", tone: "from-lime-100 to-green-50 text-lime-700" }, events: { glyph: "🎉", tone: "from-pink-100 to-yellow-50 text-pink-700" }, family: { glyph: "🧸", tone: "from-yellow-100 to-pink-50 text-amber-700" }, pets: { glyph: "🐾", tone: "from-orange-100 to-yellow-50 text-orange-700" }, agriculture: { glyph: "🌱", tone: "from-green-100 to-lime-50 text-green-700" }, industry: { glyph: "🏭", tone: "from-zinc-200 to-slate-50 text-zinc-700" }, media: { glyph: "📰", tone: "from-purple-100 to-indigo-50 text-purple-700" }, cleaning: { glyph: "✨", tone: "from-teal-100 to-cyan-50 text-teal-700" },
};
const popular = [["مدیریت اینستاگرام", "business", "instagram-management"], ["تولید محتوا", "business", "content-production"], ["میکاپ آرتیست", "beauty", "makeup-artist"], ["کراتین مو", "beauty", "hair-keratin"], ["ناخن‌کار", "beauty", "nail-salon"], ["طلافروشی", "shopping", "gold-jewelry"], ["داروخانه", "health", "pharmacy"], ["لوازم خانگی", "home", "home-appliances"]];

export default function CategoryExplorer({ categories, subcategories }: Props) {
  const [query, setQuery] = useState("");
  const [showAll, setShowAll] = useState(false);
  const normalized = query.trim().toLocaleLowerCase("fa");
  const groups = useMemo(() => categories.map((category) => {
    const children = subcategories.filter((item) => item.category_id === category.id);
    const matches = !normalized || category.name.toLocaleLowerCase("fa").includes(normalized) || children.some((item) => item.name.toLocaleLowerCase("fa").includes(normalized));
    return { category, children, matches };
  }).filter((group) => group.matches), [categories, subcategories, normalized]);
  const visible = normalized || showAll ? groups : groups.slice(0, 12);

  return <section id="categories" className="mx-auto max-w-7xl px-5 py-14 lg:px-8 lg:py-20">
    <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
      <div><p className="text-xs font-black tracking-[0.25em] text-[#c91442]">EXPLORE YOUR CITY</p><h2 className="mt-2 text-3xl font-black text-[#241b1c] sm:text-4xl">هر خدمتی، جای خودش</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[#80716f]">از دسته اصلی تا ریزترین تخصص، سریع پیدایش کن؛ بدون گشتن بین صفحه‌های نامرتبط.</p></div>
      <div className="relative w-full lg:w-[25rem]"><span className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-xl text-[#c91442]">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="مثلاً: مدیریت اینستاگرام، داروخانه..." className="h-14 w-full rounded-2xl border border-[#eadfd7] bg-white pr-12 pl-4 text-sm text-[#241b1c] outline-none shadow-[0_12px_35px_-28px_rgba(77,30,36,0.8)] transition focus:border-[#c91442] focus:ring-4 focus:ring-[#c91442]/10" /></div>
    </div>
    <div className="mt-6 flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-[#9a8985]">جست‌وجوی سریع:</span>{popular.map(([label, category, sub]) => <Link key={sub} href={'/category/' + category + '/' + sub} className="rounded-full border border-[#eadfd7] bg-white px-3 py-2 text-xs font-bold text-[#665655] transition hover:-translate-y-0.5 hover:border-[#c91442]/40 hover:text-[#c91442]">{label}</Link>)}</div>
    <div className="mt-9 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {visible.map(({ category, children }) => { const visual = visuals[category.slug] || { glyph: category.icon || "✦", tone: "from-[#f9e4e9] to-white text-[#c91442]" }; const shownChildren = normalized ? children.filter((item) => item.name.toLocaleLowerCase("fa").includes(normalized)) : children; return <article key={category.id} className="group rounded-[1.5rem] border border-[#eadfd7] bg-white p-4 shadow-[0_12px_35px_-30px_rgba(77,30,36,0.9)] transition duration-200 hover:-translate-y-1 hover:border-[#c91442]/35 hover:shadow-[0_20px_45px_-28px_rgba(201,20,66,0.35)]"><div className="flex items-center justify-between gap-3"><Link href={'/category/' + category.slug} className="flex min-w-0 items-center gap-3"><span className={'grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br text-2xl ' + visual.tone}>{visual.glyph}</span><span className="min-w-0"><span className="block truncate font-black text-[#332526] group-hover:text-[#c91442]">{category.name}</span><span className="mt-1 block text-xs text-[#9a8985]">{children.length} خدمت تخصصی</span></span></Link><Link href={'/category/' + category.slug} aria-label={'مشاهده ' + category.name} className="text-lg text-[#c91442] transition group-hover:-translate-x-1">←</Link></div><div className="mt-4 flex flex-wrap gap-1.5">{(shownChildren.length ? shownChildren : children).slice(0, 5).map((item) => <Link key={item.id} href={'/category/' + category.slug + '/' + item.slug} className="rounded-lg bg-[#fff8f5] px-2.5 py-1.5 text-[11px] font-bold text-[#796966] transition hover:bg-[#f9e4e9] hover:text-[#b6113d]">{item.name}</Link>)}{children.length > 5 && <Link href={'/category/' + category.slug} className="rounded-lg bg-[#f6f1ee] px-2.5 py-1.5 text-[11px] font-black text-[#c91442]">+{children.length - 5} مورد</Link>}</div></article>; })}
    </div>
    {visible.length === 0 && <div className="rounded-3xl border border-dashed border-[#d8c8c2] bg-[#fffaf7] py-14 text-center"><p className="font-black text-[#3b2d2e]">چیزی با این عبارت پیدا نشد.</p><p className="mt-2 text-sm text-[#8a7b79]">نام دسته یا تخصص را کوتاه‌تر بنویس یا از پیشنهادهای بالا انتخاب کن.</p></div>}
    {groups.length > 12 && !normalized && <button onClick={() => setShowAll((value) => !value)} className="mx-auto mt-8 flex items-center gap-2 rounded-full border border-[#c91442]/25 bg-white px-5 py-3 text-sm font-black text-[#c91442] transition hover:bg-[#fff6f8]">{showAll ? "نمایش کمتر" : 'نمایش همه دسته‌ها (' + groups.length + ')'}<span>{showAll ? "↑" : "↓"}</span></button>}
  </section>;
}
