/**
 * 300 named areas transcribed from the user-provided DOCX. The document itself
 * says this is a shortlist, not an official or complete municipal register.
 * Center coordinates are intentionally not inferred from names.
 */
export type NeighborhoodCatalogEntry = { citySlug: string; name: string; slug: string };

export const neighborhoodCatalog: NeighborhoodCatalogEntry[] = [
  { citySlug: "tehran", name: "تجریش", slug: "tjrish" },
  { citySlug: "tehran", name: "ونک", slug: "onk" },
  { citySlug: "tehran", name: "شهرک غرب (دریا)", slug: "shhrk-ghrb-dria" },
  { citySlug: "tehran", name: "پونک", slug: "ponk" },
  { citySlug: "tehran", name: "سعادت‌آباد", slug: "sadt-abad" },
  { citySlug: "tehran", name: "نیاوران", slug: "niaoran" },
  { citySlug: "tehran", name: "الهیه", slug: "alhih" },
  { citySlug: "tehran", name: "زعفرانیه", slug: "zfranih" },
  { citySlug: "tehran", name: "جردن", slug: "jrdn" },
  { citySlug: "tehran", name: "یوسف‌آباد", slug: "iosf-abad" },
  { citySlug: "tehran", name: "امیرآباد", slug: "amirabad" },
  { citySlug: "tehran", name: "شهرآرا", slug: "shhrara" },
  { citySlug: "tehran", name: "نارمک", slug: "narmk" },
  { citySlug: "tehran", name: "تهرانپارس", slug: "thranpars" },
  { citySlug: "tehran", name: "پاسداران", slug: "pasdaran" },
  { citySlug: "tehran", name: "ولنجک", slug: "olnjk" },
  { citySlug: "tehran", name: "قیطریه", slug: "qitrih" },
  { citySlug: "tehran", name: "دروس", slug: "dros" },
  { citySlug: "tehran", name: "فرمانیه", slug: "frmanih" },
  { citySlug: "tehran", name: "اکباتان", slug: "akbatan" },
  { citySlug: "tehran", name: "شهران", slug: "shhran" },
  { citySlug: "tehran", name: "آجودانیه", slug: "ajodanih" },
  { citySlug: "tehran", name: "میرداماد", slug: "mirdamad" },
  { citySlug: "tehran", name: "صادقیه", slug: "sadqih" },
  { citySlug: "tehran", name: "سهروردی", slug: "shrordi" },
  { citySlug: "tehran", name: "جنت‌آباد", slug: "jnt-abad" },
  { citySlug: "tehran", name: "هفت‌تیر", slug: "hft-tir" },
  { citySlug: "tehran", name: "امیریه", slug: "amirih" },
  { citySlug: "tehran", name: "حکیمیه", slug: "hkimih" },
  { citySlug: "tehran", name: "نازی‌آباد", slug: "nazi-abad" },
  { citySlug: "tehran", name: "خزانه", slug: "khzanh" },
  { citySlug: "tehran", name: "هروی", slug: "hroi" },
  { citySlug: "tehran", name: "مولوی", slug: "moloi" },
  { citySlug: "tehran", name: "سنگلج", slug: "snglj" },
  { citySlug: "tehran", name: "عودلاجان", slug: "odlajan" },
  { citySlug: "tehran", name: "پامنار", slug: "pamnar" },
  { citySlug: "tehran", name: "چیتگر", slug: "chitgr" },
  { citySlug: "tehran", name: "یافت‌آباد", slug: "iaft-abad" },
  { citySlug: "tehran", name: "ستارخان", slug: "starkhan" },
  { citySlug: "tehran", name: "گیشا", slug: "gisha" },
  { citySlug: "tehran", name: "تهران‌ویلا", slug: "thran-oila" },
  { citySlug: "tehran", name: "شریف‌آباد", slug: "shrif-abad" },
  { citySlug: "mashhad", name: "سجاد", slug: "sjad" },
  { citySlug: "mashhad", name: "وکیل‌آباد", slug: "okil-abad" },
  { citySlug: "mashhad", name: "احمدآباد", slug: "ahmdabad" },
  { citySlug: "mashhad", name: "کوه‌سنگی", slug: "koh-sngi" },
  { citySlug: "mashhad", name: "قاسم‌آباد", slug: "qasm-abad" },
  { citySlug: "mashhad", name: "هاشمیه", slug: "hashmih" },
  { citySlug: "mashhad", name: "طرقبه", slug: "trqbh" },
  { citySlug: "mashhad", name: "امامیه", slug: "amamih" },
  { citySlug: "mashhad", name: "ثامن", slug: "samn" },
  { citySlug: "mashhad", name: "رضاشهر", slug: "rzashhr" },
  { citySlug: "mashhad", name: "پنج‌تن", slug: "pnj-tn" },
  { citySlug: "mashhad", name: "گاز", slug: "gaz" },
  { citySlug: "mashhad", name: "توس", slug: "tos" },
  { citySlug: "mashhad", name: "الهیه", slug: "alhih" },
  { citySlug: "mashhad", name: "سناباد", slug: "snabad" },
  { citySlug: "mashhad", name: "بلوار معلم", slug: "bloar-mlm" },
  { citySlug: "mashhad", name: "ملک‌آباد", slug: "mlk-abad" },
  { citySlug: "mashhad", name: "طلاب", slug: "tlab" },
  { citySlug: "mashhad", name: "فرهنگ", slug: "frhng" },
  { citySlug: "mashhad", name: "چهارراه شهدا", slug: "chharrah-shhda" },
  { citySlug: "mashhad", name: "نوفل‌لوشاتو", slug: "nofl-loshato" },
  { citySlug: "mashhad", name: "مدرس", slug: "mdrs" },
  { citySlug: "isfahan", name: "چهارباغ", slug: "chharbagh" },
  { citySlug: "isfahan", name: "جلفا", slug: "jlfa" },
  { citySlug: "isfahan", name: "جی", slug: "ji" },
  { citySlug: "isfahan", name: "سپاهان‌شهر", slug: "spahan-shhr" },
  { citySlug: "isfahan", name: "کاوه", slug: "kaoh" },
  { citySlug: "isfahan", name: "احمدآباد", slug: "ahmdabad" },
  { citySlug: "isfahan", name: "مرداویج", slug: "mrdaoij" },
  { citySlug: "isfahan", name: "شهشهان", slug: "shhshhan" },
  { citySlug: "isfahan", name: "بزرگمهر", slug: "bzrgmhr" },
  { citySlug: "isfahan", name: "آتشگاه", slug: "atshgah" },
  { citySlug: "isfahan", name: "دروازه شیراز", slug: "droazh-shiraz" },
  { citySlug: "isfahan", name: "دردشت", slug: "drdsht" },
  { citySlug: "isfahan", name: "رهنان", slug: "rhnan" },
  { citySlug: "isfahan", name: "نظر", slug: "nzr" },
  { citySlug: "isfahan", name: "تخت فولاد", slug: "tkht-folad" },
  { citySlug: "isfahan", name: "دستگرد", slug: "dstgrd" },
  { citySlug: "isfahan", name: "ملک‌شهر", slug: "mlk-shhr" },
  { citySlug: "isfahan", name: "پل‌شهرستان", slug: "pl-shhrstan" },
  { citySlug: "isfahan", name: "هزار جریب", slug: "hzar-jrib" },
  { citySlug: "karaj", name: "گوهردشت", slug: "gohrdsht" },
  { citySlug: "karaj", name: "مهرشهر", slug: "mhrshhr" },
  { citySlug: "karaj", name: "عظیمیه", slug: "zimih" },
  { citySlug: "karaj", name: "فردیس", slug: "frdis" },
  { citySlug: "karaj", name: "کمال‌شهر", slug: "kmal-shhr" },
  { citySlug: "karaj", name: "جهان‌شهر", slug: "jhan-shhr" },
  { citySlug: "karaj", name: "حصارک", slug: "hsark" },
  { citySlug: "karaj", name: "شاهین‌ویلا", slug: "shahin-oila" },
  { citySlug: "karaj", name: "باغستان", slug: "baghstan" },
  { citySlug: "karaj", name: "رجایی‌شهر", slug: "rjaii-shhr" },
  { citySlug: "karaj", name: "مهردشت", slug: "mhrdsht" },
  { citySlug: "karaj", name: "گلشهر", slug: "glshhr" },
  { citySlug: "karaj", name: "مارلیک", slug: "marlik" },
  { citySlug: "karaj", name: "سیمین‌دشت", slug: "simin-dsht" },
  { citySlug: "shiraz", name: "معالی‌آباد", slug: "mali-abad" },
  { citySlug: "shiraz", name: "قصردشت", slug: "qsrdsht" },
  { citySlug: "shiraz", name: "زرگری", slug: "zrgri" },
  { citySlug: "shiraz", name: "سعدی", slug: "sdi" },
  { citySlug: "shiraz", name: "چمران", slug: "chmran" },
  { citySlug: "shiraz", name: "ملاصدرا", slug: "mlasdra" },
  { citySlug: "shiraz", name: "گلدشت", slug: "gldsht" },
  { citySlug: "shiraz", name: "ستارخان", slug: "starkhan" },
  { citySlug: "shiraz", name: "فرهنگ‌شهر", slug: "frhng-shhr" },
  { citySlug: "shiraz", name: "بوستان", slug: "bostan" },
  { citySlug: "shiraz", name: "قدوسی", slug: "qdosi" },
  { citySlug: "shiraz", name: "باغ‌تخت", slug: "bagh-tkht" },
  { citySlug: "shiraz", name: "شهرک گلستان", slug: "shhrk-glstan" },
  { citySlug: "shiraz", name: "میدان ارم", slug: "midan-arm" },
  { citySlug: "tabriz", name: "ولیعصر", slug: "olisr" },
  { citySlug: "tabriz", name: "ائل‌گلی", slug: "ael-gli" },
  { citySlug: "tabriz", name: "ولیامر", slug: "oliamr" },
  { citySlug: "tabriz", name: "رشدیه", slug: "rshdih" },
  { citySlug: "tabriz", name: "باغمیشه", slug: "baghmishh" },
  { citySlug: "tabriz", name: "آبرسان", slug: "abrsan" },
  { citySlug: "tabriz", name: "عباسی", slug: "basi" },
  { citySlug: "tabriz", name: "یاغچیان", slug: "iaghchian" },
  { citySlug: "tabriz", name: "آخماقیه", slug: "akhmaqih" },
  { citySlug: "tabriz", name: "ششگلان", slug: "shshglan" },
  { citySlug: "tabriz", name: "منظریه", slug: "mnzrih" },
  { citySlug: "tabriz", name: "مارالان", slug: "maralan" },
  { citySlug: "tabriz", name: "شریعتی", slug: "shriti" },
  { citySlug: "qom", name: "صفاییه", slug: "sfaiih" },
  { citySlug: "qom", name: "پردیسان", slug: "prdisan" },
  { citySlug: "qom", name: "نیروگاه", slug: "nirogah" },
  { citySlug: "qom", name: "زنبیل‌آباد", slug: "znbil-abad" },
  { citySlug: "qom", name: "انصاریان", slug: "ansarian" },
  { citySlug: "qom", name: "ایستگاه", slug: "aistgah" },
  { citySlug: "qom", name: "چهارمردان", slug: "chharmrdan" },
  { citySlug: "qom", name: "شاهزاده ابراهیم", slug: "shahzadh-abrahim" },
  { citySlug: "qom", name: "توحید", slug: "tohid" },
  { citySlug: "qom", name: "سالاریه", slug: "salarih" },
  { citySlug: "qom", name: "شهرک قدس", slug: "shhrk-qds" },
  { citySlug: "qom", name: "پیامبر اعظم", slug: "piambr-azm" },
  { citySlug: "ahvaz", name: "کیانپارس", slug: "kianpars" },
  { citySlug: "ahvaz", name: "کیان‌آباد", slug: "kian-abad" },
  { citySlug: "ahvaz", name: "زیتون کارمندی", slug: "ziton-karmndi" },
  { citySlug: "ahvaz", name: "گلستان", slug: "glstan" },
  { citySlug: "ahvaz", name: "ملی‌راه", slug: "mli-rah" },
  { citySlug: "ahvaz", name: "کوروش", slug: "korosh" },
  { citySlug: "ahvaz", name: "امانیه", slug: "amanih" },
  { citySlug: "ahvaz", name: "لشگرآباد", slug: "lshgrabad" },
  { citySlug: "ahvaz", name: "سیاحی", slug: "siahi" },
  { citySlug: "ahvaz", name: "چهار شیر", slug: "chhar-shir" },
  { citySlug: "ahvaz", name: "نادری", slug: "nadri" },
  { citySlug: "ahvaz", name: "عامری", slug: "amri" },
  { citySlug: "ahvaz", name: "حصیرآباد", slug: "hsirabad" },
  { citySlug: "ahvaz", name: "ناصری", slug: "nasri" },
  { citySlug: "ahvaz", name: "شهرک نفت", slug: "shhrk-nft" },
  { citySlug: "kermanshah", name: "طاق‌بستان", slug: "taq-bstan" },
  { citySlug: "kermanshah", name: "کوی نواب", slug: "koi-noab" },
  { citySlug: "kermanshah", name: "دولت‌آباد", slug: "dolt-abad" },
  { citySlug: "kermanshah", name: "کوی ولیعصر", slug: "koi-olisr" },
  { citySlug: "kermanshah", name: "کیانشهر", slug: "kianshhr" },
  { citySlug: "kermanshah", name: "باغ ابریشم", slug: "bagh-abrishm" },
  { citySlug: "kermanshah", name: "شاطرآباد", slug: "shatrabad" },
  { citySlug: "kermanshah", name: "فرهنگیان", slug: "frhngian" },
  { citySlug: "kermanshah", name: "میدان آزادی", slug: "midan-azadi" },
  { citySlug: "kermanshah", name: "بلوار شهید بهشتی", slug: "bloar-shhid-bhshti" },
  { citySlug: "urmia", name: "نازلو", slug: "nazlo" },
  { citySlug: "urmia", name: "شهرک ولیعصر", slug: "shhrk-olisr" },
  { citySlug: "urmia", name: "فرهنگیان", slug: "frhngian" },
  { citySlug: "urmia", name: "سیلو", slug: "silo" },
  { citySlug: "urmia", name: "خیابان مدنی", slug: "khiaban-mdni" },
  { citySlug: "urmia", name: "شهرک انقلاب", slug: "shhrk-anqlab" },
  { citySlug: "rasht", name: "گلسار", slug: "glsar" },
  { citySlug: "rasht", name: "منظریه", slug: "mnzrih" },
  { citySlug: "rasht", name: "سبزه‌میدان", slug: "sbzh-midan" },
  { citySlug: "rasht", name: "لاکان", slug: "lakan" },
  { citySlug: "rasht", name: "ساغریسازان", slug: "saghrisazan" },
  { citySlug: "rasht", name: "بلوار انصاری", slug: "bloar-ansari" },
  { citySlug: "rasht", name: "خیابان معلم", slug: "khiaban-mlm" },
  { citySlug: "rasht", name: "میدان شهرداری", slug: "midan-shhrdari" },
  { citySlug: "rasht", name: "ریل‌سازی", slug: "ril-sazi" },
  { citySlug: "rasht", name: "کوچ‌صفهان", slug: "koch-sfhan" },
  { citySlug: "zahedan", name: "خیابان سعدی", slug: "khiaban-sdi" },
  { citySlug: "zahedan", name: "خیابان دانشگاه", slug: "khiaban-danshgah" },
  { citySlug: "zahedan", name: "شهرک امام خمینی", slug: "shhrk-amam-khmini" },
  { citySlug: "zahedan", name: "شهرک مهدیه", slug: "shhrk-mhdih" },
  { citySlug: "zahedan", name: "کوی مهرگان", slug: "koi-mhrgan" },
  { citySlug: "zahedan", name: "خیابان خلیج فارس", slug: "khiaban-khlij-fars" },
  { citySlug: "kerman", name: "شهرک شهید چمران", slug: "shhrk-shhid-chmran" },
  { citySlug: "kerman", name: "شهرک صنعتی", slug: "shhrk-snti" },
  { citySlug: "kerman", name: "خیابان شریعتی", slug: "khiaban-shriti" },
  { citySlug: "kerman", name: "ماهان", slug: "mahan" },
  { citySlug: "kerman", name: "کوی کشاورز", slug: "koi-kshaorz" },
  { citySlug: "kerman", name: "بلوار جمهوری", slug: "bloar-jmhori" },
  { citySlug: "kerman", name: "میدان آزادی", slug: "midan-azadi" },
  { citySlug: "kerman", name: "خیابان مطهری", slug: "khiaban-mthri" },
  { citySlug: "kerman", name: "گلدشت", slug: "gldsht" },
  { citySlug: "hamedan", name: "میدان امام", slug: "midan-amam" },
  { citySlug: "hamedan", name: "خیابان باباطاهر", slug: "khiaban-babatahr" },
  { citySlug: "hamedan", name: "شهرک مدنی", slug: "shhrk-mdni" },
  { citySlug: "hamedan", name: "شهرک مهدیه", slug: "shhrk-mhdih" },
  { citySlug: "hamedan", name: "بلوار آیت‌الله مدنی", slug: "bloar-ait-allh-mdni" },
  { citySlug: "hamedan", name: "خیابان شریعتی", slug: "khiaban-shriti" },
  { citySlug: "hamedan", name: "گنجنامه", slug: "gnjnamh" },
  { citySlug: "hamedan", name: "خیابان بوعلی", slug: "khiaban-boli" },
  { citySlug: "hamedan", name: "میدان ۱۳ آبان", slug: "midan-13-aban" },
  { citySlug: "yazd", name: "فهادان", slug: "fhadan" },
  { citySlug: "yazd", name: "دروازه قرآن", slug: "droazh-qran" },
  { citySlug: "yazd", name: "شاهدی", slug: "shahdi" },
  { citySlug: "yazd", name: "میدان امیرچخماق", slug: "midan-amirchkhmaq" },
  { citySlug: "yazd", name: "صفائیه", slug: "sfaeih" },
  { citySlug: "yazd", name: "شهرک امام حسین", slug: "shhrk-amam-hsin" },
  { citySlug: "yazd", name: "بلوار جمهوری", slug: "bloar-jmhori" },
  { citySlug: "yazd", name: "خیابان کاشانی", slug: "khiaban-kashani" },
  { citySlug: "yazd", name: "شهرک مصلی", slug: "shhrk-msli" },
  { citySlug: "yazd", name: "کوی ولیعصر", slug: "koi-olisr" },
  { citySlug: "ardabil", name: "خیابان ارشاد", slug: "khiaban-arshad" },
  { citySlug: "ardabil", name: "خیابان امام", slug: "khiaban-amam" },
  { citySlug: "ardabil", name: "شهرک خلیل‌آباد", slug: "shhrk-khlil-abad" },
  { citySlug: "ardabil", name: "بلوار دانشگاه", slug: "bloar-danshgah" },
  { citySlug: "ardabil", name: "خیابان جمهوری", slug: "khiaban-jmhori" },
  { citySlug: "ardabil", name: "میدان بسیج", slug: "midan-bsij" },
  { citySlug: "ardabil", name: "کوی ولیعصر", slug: "koi-olisr" },
  { citySlug: "bandar-abbas", name: "شهرک نگین", slug: "shhrk-ngin" },
  { citySlug: "bandar-abbas", name: "میدان امام حسین", slug: "midan-amam-hsin" },
  { citySlug: "bandar-abbas", name: "خیابان شهید چمران", slug: "khiaban-shhid-chmran" },
  { citySlug: "bandar-abbas", name: "شهرک خلیج فارس", slug: "shhrk-khlij-fars" },
  { citySlug: "bandar-abbas", name: "کوی ولیعصر", slug: "koi-olisr" },
  { citySlug: "bandar-abbas", name: "میدان شهدا", slug: "midan-shhda" },
  { citySlug: "bandar-abbas", name: "سورو", slug: "soro" },
  { citySlug: "arak", name: "خیابان شریعتی", slug: "khiaban-shriti" },
  { citySlug: "arak", name: "شهرک امام خمینی", slug: "shhrk-amam-khmini" },
  { citySlug: "arak", name: "بلوار شهید بهشتی", slug: "bloar-shhid-bhshti" },
  { citySlug: "arak", name: "خیابان مدرس", slug: "khiaban-mdrs" },
  { citySlug: "arak", name: "میدان امام", slug: "midan-amam" },
  { citySlug: "arak", name: "شهرک قدس", slug: "shhrk-qds" },
  { citySlug: "arak", name: "خیابان سردار جنگل", slug: "khiaban-srdar-jngl" },
  { citySlug: "zanjan", name: "خیابان امام", slug: "khiaban-amam" },
  { citySlug: "zanjan", name: "شهرک ولیعصر", slug: "shhrk-olisr" },
  { citySlug: "zanjan", name: "میدان ولیعصر", slug: "midan-olisr" },
  { citySlug: "zanjan", name: "خیابان شهید بهشتی", slug: "khiaban-shhid-bhshti" },
  { citySlug: "zanjan", name: "شهرک مهدیه", slug: "shhrk-mhdih" },
  { citySlug: "zanjan", name: "کوی ارم", slug: "koi-arm" },
  { citySlug: "sanandaj", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "sanandaj", name: "خیابان پاسداران", slug: "khiaban-pasdaran" },
  { citySlug: "sanandaj", name: "بلوار کردستان", slug: "bloar-krdstan" },
  { citySlug: "sanandaj", name: "خیابان ۱۷ شهریور", slug: "khiaban-17-shhrior" },
  { citySlug: "sanandaj", name: "شهرک ولیعصر", slug: "shhrk-olisr" },
  { citySlug: "sanandaj", name: "بلوار بهار", slug: "bloar-bhar" },
  { citySlug: "qazvin", name: "شهرک عصر انقلاب", slug: "shhrk-sr-anqlab" },
  { citySlug: "qazvin", name: "بلوار شهید بهشتی", slug: "bloar-shhid-bhshti" },
  { citySlug: "qazvin", name: "خیابان مولوی", slug: "khiaban-moloi" },
  { citySlug: "qazvin", name: "میدان آزادی", slug: "midan-azadi" },
  { citySlug: "qazvin", name: "شهرک مهدیه", slug: "shhrk-mhdih" },
  { citySlug: "qazvin", name: "خیابان انقلاب", slug: "khiaban-anqlab" },
  { citySlug: "khorramabad", name: "خیابان شریعتی", slug: "khiaban-shriti" },
  { citySlug: "khorramabad", name: "شهرک ولیعصر", slug: "shhrk-olisr" },
  { citySlug: "khorramabad", name: "بلوار مدرس", slug: "bloar-mdrs" },
  { citySlug: "khorramabad", name: "شهرک انقلاب", slug: "shhrk-anqlab" },
  { citySlug: "khorramabad", name: "کوی رازی", slug: "koi-razi" },
  { citySlug: "khorramabad", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "gorgan", name: "خیابان ولیعصر", slug: "khiaban-olisr" },
  { citySlug: "gorgan", name: "شهرک نبوت", slug: "shhrk-nbot" },
  { citySlug: "gorgan", name: "بلوار شهید بهشتی", slug: "bloar-shhid-bhshti" },
  { citySlug: "gorgan", name: "شهرک هلال احمر", slug: "shhrk-hlal-ahmr" },
  { citySlug: "gorgan", name: "خیابان شریعتی", slug: "khiaban-shriti" },
  { citySlug: "gorgan", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "sari", name: "خیابان فرهنگ", slug: "khiaban-frhng" },
  { citySlug: "sari", name: "شهرک امام خمینی", slug: "shhrk-amam-khmini" },
  { citySlug: "sari", name: "خیابان طالب آملی", slug: "khiaban-talb-amli" },
  { citySlug: "sari", name: "میدان امام", slug: "midan-amam" },
  { citySlug: "sari", name: "بلوار خزر", slug: "bloar-khzr" },
  { citySlug: "sari", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "bushehr", name: "شهرک کوثر", slug: "shhrk-kosr" },
  { citySlug: "bushehr", name: "کوی ولیعصر", slug: "koi-olisr" },
  { citySlug: "bushehr", name: "خیابان امام", slug: "khiaban-amam" },
  { citySlug: "bushehr", name: "میدان ولیعصر", slug: "midan-olisr" },
  { citySlug: "bushehr", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "bushehr", name: "بلوار ساحلی", slug: "bloar-sahli" },
  { citySlug: "birjand", name: "خیابان معلم", slug: "khiaban-mlm" },
  { citySlug: "birjand", name: "شهرک ولیعصر", slug: "shhrk-olisr" },
  { citySlug: "birjand", name: "بلوار غفاری", slug: "bloar-ghfari" },
  { citySlug: "birjand", name: "میدان مصلی", slug: "midan-msli" },
  { citySlug: "birjand", name: "خیابان مدرس", slug: "khiaban-mdrs" },
  { citySlug: "birjand", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "ilam", name: "شهرک امام خمینی", slug: "shhrk-amam-khmini" },
  { citySlug: "ilam", name: "بلوار شهید بهشتی", slug: "bloar-shhid-bhshti" },
  { citySlug: "ilam", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "ilam", name: "خیابان ولیعصر", slug: "khiaban-olisr" },
  { citySlug: "ilam", name: "کوی ولیعصر", slug: "koi-olisr" },
  { citySlug: "shahrekord", name: "خیابان امام", slug: "khiaban-amam" },
  { citySlug: "shahrekord", name: "شهرک ولیعصر", slug: "shhrk-olisr" },
  { citySlug: "shahrekord", name: "بلوار مدرس", slug: "bloar-mdrs" },
  { citySlug: "shahrekord", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "shahrekord", name: "میدان آزادی", slug: "midan-azadi" },
  { citySlug: "yasuj", name: "بلوار شهید بهشتی", slug: "bloar-shhid-bhshti" },
  { citySlug: "yasuj", name: "خیابان امام", slug: "khiaban-amam" },
  { citySlug: "yasuj", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "yasuj", name: "خیابان شریعتی", slug: "khiaban-shriti" },
  { citySlug: "yasuj", name: "شهرک ولیعصر", slug: "shhrk-olisr" },
  { citySlug: "semnan", name: "خیابان امام", slug: "khiaban-amam" },
  { citySlug: "semnan", name: "بلوار ولیعصر", slug: "bloar-olisr" },
  { citySlug: "semnan", name: "شهرک فرهنگیان", slug: "shhrk-frhngian" },
  { citySlug: "semnan", name: "خیابان مدرس", slug: "khiaban-mdrs" },
  { citySlug: "semnan", name: "شهرک امام خمینی", slug: "shhrk-amam-khmini" },
];
