import { Business, Category, Subcategory } from "./types";

export const seedCategories: Category[] = [
  ["غذا و نوشیدنی", "food", "🍽️"],
  ["خرید و فروشگاه", "shopping", "🛍️"],
  ["مد و پوشاک", "fashion", "👗"],
  ["زیبایی", "beauty", "✂️"],
  ["سلامت و درمان", "health", "⚕️"],
  ["آموزش", "education", "🎓"],
  ["خانه و دکوراسیون", "home", "⌂"],
  ["خودرو و حمل‌ونقل", "automotive", "🚗"],
  ["سفر و اقامت", "travel", "✈️"],
  ["ورزش", "sport", "🏃"],
  ["هنر و فرهنگ", "culture", "🎨"],
  ["خدمات فنی", "technical", "🔧"],
  ["کسب‌وکار و بازاریابی", "business", "◈"],
  ["فناوری", "technology", "⌘"],
  ["مالی و حسابداری", "finance", "₿"],
  ["حقوقی", "legal", "§"],
  ["املاک و ساختمان", "real-estate", "⌂"],
  ["مراسم و رویداد", "events", "✦"],
  ["کودک و خانواده", "family", "♡"],
  ["حیوانات خانگی", "pets", "♧"],
  ["کشاورزی", "agriculture", "♧"],
  ["صنعت و تولید", "industry", "▦"],
  ["رسانه و چاپ", "media", "▤"],
  ["نظافت و خدمات منزل", "cleaning", "✧"],
].map(([name, slug, icon], index) => ({ id: `c${index + 1}`, name, slug, icon }));

const categorySubcategories: Record<string, Array<[string, string]>> = {
  c1: [["کافه", "cafe"], ["رستوران", "restaurant"], ["فست‌فود", "fast-food"], ["بیکری و شیرینی", "bakery"], ["کترینگ", "catering"], ["آبمیوه و بستنی", "juice-icecream"]],
  c2: [["سوپرمارکت", "supermarket"], ["فروشگاه زنجیره‌ای", "chain-store"], ["کتاب‌فروشی", "bookstore"], ["لوازم تحریر", "stationery"], ["هدیه و کادو", "gift"], ["فروشگاه تخصصی", "specialty-store"]],
  c3: [["لباس زنانه", "womens-clothing"], ["لباس مردانه", "mens-clothing"], ["لباس کودک", "kids-clothing"], ["کیف و کفش", "bags-shoes"], ["پارچه", "fabric"], ["خیاطی", "tailoring"]],
  c4: [["آرایشگاه زنانه", "womens-salon"], ["آرایشگاه مردانه", "mens-salon"], ["ناخن و مژه", "nails-lashes"], ["اسپا و ماساژ", "spa-massage"], ["میکاپ", "makeup"], ["پوست و مو", "skin-hair"]],
  c5: [["پزشک", "doctor"], ["دندان‌پزشکی", "dentistry"], ["داروخانه", "pharmacy"], ["آزمایشگاه", "laboratory"], ["فیزیوتراپی", "physiotherapy"], ["روان‌شناسی", "psychology"]],
  c6: [["آموزش زبان", "language"], ["کنکور و تقویتی", "exam-prep"], ["موسیقی", "music-class"], ["هنر", "art-class"], ["برنامه‌نویسی", "coding"], ["مهارت‌های شغلی", "career-skills"]],
  c7: [["مبلمان", "furniture"], ["دکوراسیون داخلی", "interior-design"], ["لوازم خانگی", "home-appliances"], ["دکور و اکسسوری", "decor"], ["کابینت", "cabinetry"], ["گل و گیاه", "plants"]],
  c8: [["تعمیر خودرو", "car-repair"], ["کارواش", "car-wash"], ["لاستیک و رینگ", "tires"], ["قطعات خودرو", "auto-parts"], ["کرایه خودرو", "car-rental"], ["باربری", "freight"]],
  c9: [["هتل", "hotel"], ["اقامتگاه بوم‌گردی", "eco-lodge"], ["آژانس مسافرتی", "travel-agency"], ["تور", "tour"], ["بلیط", "tickets"], ["راهنمای گردشگری", "tour-guide"]],
  c10: [["باشگاه بدنسازی", "gym"], ["سوارکاری", "equestrian"], ["فوتبال", "football"], ["یوگا", "yoga"], ["شنا", "swimming"], ["لوازم کوهنوردی", "mountaineering"]],
  c11: [["گالری", "gallery"], ["عکاسی", "photography"], ["سینما و تئاتر", "cinema-theater"], ["کتاب و نشر", "publishing"], ["صنایع‌دستی", "handicraft"], ["موسیقی", "music"]],
  c12: [["تأسیسات", "installations"], ["برق‌کاری", "electrician"], ["لوله‌کشی", "plumbing"], ["نجاری", "carpentry"], ["تعمیرات لوازم", "appliance-repair"], ["قفل و کلید", "locksmith"]],
  c13: [["دیجیتال مارکتینگ", "digital-marketing"], ["برندسازی", "branding"], ["طراحی سایت", "web-design"], ["تبلیغات", "advertising"], ["مشاوره کسب‌وکار", "business-consulting"], ["تولید محتوا", "content-production"]],
  c14: [["فروشگاه موبایل", "mobile-store"], ["تعمیرات موبایل", "mobile-repair"], ["خدمات کامپیوتری", "computer-services"], ["نرم‌افزار", "software"], ["امنیت شبکه", "cybersecurity"], ["هوش مصنوعی", "ai"]],
  c15: [["حسابداری", "accounting"], ["حسابرسی", "audit"], ["بیمه", "insurance"], ["وام و اعتبار", "credit"], ["مشاوره مالی", "financial-advice"], ["صرافی", "exchange"]],
  c16: [["وکیل", "lawyer"], ["دفتر اسناد رسمی", "notary"], ["مشاوره حقوقی", "legal-consulting"], ["ثبت شرکت", "company-registration"], ["داوری", "arbitration"], ["مهاجرت", "immigration"]],
  c17: [["مشاور املاک", "real-estate-agency"], ["معماری", "architecture"], ["ساخت‌وساز", "construction"], ["دکوراسیون", "renovation"], ["مصالح ساختمانی", "building-materials"], ["تأسیسات ساختمان", "building-installations"]],
  c18: [["تشریفات", "ceremony"], ["تالار", "hall"], ["برگزاری نمایشگاه", "exhibition"], ["گل‌آرایی", "floristry"], ["موسیقی مراسم", "event-music"], ["عکاسی مراسم", "event-photography"]],
  c19: [["مهدکودک", "kindergarten"], ["اسباب‌بازی", "toys"], ["مشاوره خانواده", "family-consulting"], ["لباس کودک", "kids-fashion"], ["کلاس کودک", "kids-class"], ["پرستاری کودک", "childcare"]],
  c20: [["کلینیک حیوانات", "vet"], ["پت‌شاپ", "pet-shop"], ["پانسیون حیوانات", "pet-boarding"], ["آرایش حیوانات", "pet-grooming"], ["غذای حیوانات", "pet-food"], ["آموزش حیوانات", "pet-training"]],
  c21: [["نهال و گلخانه", "nursery"], ["ماشین‌آلات کشاورزی", "farm-machinery"], ["محصولات ارگانیک", "organic"], ["دام و طیور", "livestock"], ["خدمات باغبانی", "gardening"], ["زنبورداری", "beekeeping"]],
  c22: [["کارخانه", "factory"], ["قطعات صنعتی", "industrial-parts"], ["ماشین‌آلات", "machinery"], ["بسته‌بندی", "packaging"], ["مواد اولیه", "raw-materials"], ["تولید سفارشی", "custom-production"]],
  c23: [["چاپخانه", "printing"], ["طراحی گرافیک", "graphic-design"], ["خبرگزاری", "news-agency"], ["استودیو", "studio"], ["تبلیغات محیطی", "outdoor-ads"], ["ترجمه", "translation"]],
  c24: [["نظافت منزل", "home-cleaning"], ["قالیشویی", "carpet-cleaning"], ["اسباب‌کشی", "moving"], ["خدمات باغبانی", "home-gardening"], ["خدمات پرستاری", "home-care"], ["خدمات خشکشویی", "laundry"]],
};

export const seedSubcategories: Subcategory[] = Object.entries(categorySubcategories).flatMap(
  ([category_id, items], categoryIndex) =>
    items.map(([name, slug], itemIndex) => ({
      id: `s${categoryIndex + 1}-${itemIndex + 1}`,
      category_id,
      name,
      slug,
    })),
);

export const seedBusinesses: Business[] = [
  {
    id: "b1",
    name: "باشگاه سوارکاری آفتاب",
    city_id: "mashhad",
    category_id: "c10",
    subcategory_id: "s10-2",
    address: "مشهد، بلوار وکیل‌آباد",
    lat: 36.297,
    lng: 59.556,
    phone: "09150000000",
    instagram: "aftab_equestrian",
    telegram: "aftab_equestrian",
    bale: "aftab_equestrian",
    whatsapp: "989150000000",
    neshan: null,
    hours: "۸ تا ۲۰",
    price_tier: 2,
    is_supporter: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "b2",
    name: "کافه نمور",
    city_id: "mashhad",
    category_id: "c1",
    subcategory_id: "s1-1",
    address: "مشهد، احمدآباد",
    lat: 36.303,
    lng: 59.588,
    phone: "05100000000",
    instagram: "namoor.cafe",
    telegram: "namoorcafe",
    bale: "namoorcafe",
    whatsapp: "985100000000",
    neshan: null,
    hours: "۹ تا ۲۳",
    price_tier: 1,
    is_supporter: false,
    status: "approved",
    created_at: new Date().toISOString(),
  },
];