import { Business, Category, Subcategory } from "./types";

export const seedCategories: Category[] = [
  ["غذا و نوشیدنی", "food", "🍽️"],
  ["خرید و فروشگاه", "shopping", "🛍️"],
  ["مد و پوشاک", "fashion", "👗"],
  ["زیبایی", "beauty", "✂️"],
  ["سلامت و درمان", "health", "⚕️"],
  ["آموزش", "education", "🎓"],
  ["خانه و دکوراسیون", "home", "⌂"],
  ["خودرو و حمل‌ونقل", "automotive", "🚗"],
  ["سفر و اقامت", "travel", "✈️"],
  ["ورزش", "sport", "🏃"],
  ["هنر و فرهنگ", "culture", "🎨"],
  ["خدمات فنی", "technical", "🔧"],
  ["کسب‌وکار و بازاریابی", "business", "◈"],
  ["فناوری", "technology", "⌘"],
  ["مالی و حسابداری", "finance", "₿"],
  ["حقوقی", "legal", "§"],
  ["املاک و ساختمان", "real-estate", "⌂"],
  ["مراسم و رویداد", "events", "✦"],
  ["کودک و خانواده", "family", "♡"],
  ["حیوانات خانگی", "pets", "♧"],
  ["کشاورزی", "agriculture", "♧"],
  ["صنعت و تولید", "industry", "▦"],
  ["رسانه و چاپ", "media", "▤"],
  ["نظافت و خدمات منزل", "cleaning", "✧"],
].map(([name, slug, icon], index) => ({ id: `c${index + 1}`, name, slug, icon }));

const categorySubcategories: Record<string, Array<[string, string]>> = {
  c1: [["کافه", "cafe"], ["رستوران", "restaurant"], ["فست‌فود", "fast-food"], ["ساندویچی", "sandwich"], ["بیکری و شیرینی", "bakery"], ["کترینگ", "catering"], ["آبمیوه و بستنی", "juice-icecream"], ["غذای سنتی", "traditional-food"], ["پیتزا", "pizza"], ["غذای سالم", "healthy-food"]],
  c2: [["سوپرمارکت", "supermarket"], ["فروشگاه زنجیره‌ای", "chain-store"], ["طلافروشی و جواهر", "gold-jewelry"], ["لوازم خانگی", "home-appliances"], ["لوازم آرایشی", "cosmetics"], ["کتاب‌فروشی", "bookstore"], ["لوازم تحریر", "stationery"], ["هدیه و کادو", "gift"], ["گل‌فروشی", "flower-shop"], ["فروشگاه کودک", "baby-store"], ["لوازم ورزشی", "sports-store"]],
  c3: [["لباس زنانه", "womens-clothing"], ["لباس مردانه", "mens-clothing"], ["لباس کودک", "kids-clothing"], ["کیف و کفش", "bags-shoes"], ["پارچه", "fabric"], ["خیاطی", "tailoring"], ["مزون عروس", "bridal-boutique"], ["شال و روسری", "scarves"], ["لباس زیر", "underwear"], ["بوتیک", "boutique"]],
  c4: [["آرایشگاه زنانه", "womens-salon"], ["آرایشگاه مردانه", "mens-salon"], ["میکاپ آرتیست", "makeup-artist"], ["کراتین مو", "hair-keratin"], ["متخصص رنگ مو", "hair-color"], ["ناخن‌کار", "nail-salon"], ["مژه و ابرو", "lashes-brows"], ["پاکسازی پوست", "skin-care"], ["اسپا و ماساژ", "spa-massage"], ["آرایش عروس", "bridal-makeup"]],
  c5: [["پزشک عمومی", "general-doctor"], ["پزشک متخصص", "specialist-doctor"], ["دندان‌پزشکی", "dentistry"], ["داروخانه", "pharmacy"], ["آزمایشگاه", "laboratory"], ["فیزیوتراپی", "physiotherapy"], ["روان‌شناسی", "psychology"], ["تغذیه و رژیم", "nutrition"], ["چشم‌پزشکی", "ophthalmology"], ["کلینیک", "clinic"]],
  c6: [["آموزش زبان", "language"], ["کنکور و تقویتی", "exam-prep"], ["معلم خصوصی", "private-teacher"], ["معلم ابتدایی", "elementary-teacher"], ["تدریس دانشگاهی", "university-tutor"], ["موسیقی", "music-class"], ["هنر", "art-class"], ["برنامه‌نویسی", "coding"], ["مهارت‌های شغلی", "career-skills"], ["آموزش رانندگی", "driving-school"], ["مهدکودک", "kindergarten"]],
  c7: [["مبلمان", "furniture"], ["دکوراسیون داخلی", "interior-design"], ["لوازم خانگی", "home-appliances"], ["دکور و اکسسوری", "decor"], ["کابینت", "cabinetry"], ["گل و گیاه", "plants"], ["پرده", "curtains"], ["فرش و موکت", "carpet"], ["نورپردازی", "lighting"], ["تشک و کالای خواب", "mattress"]],
  c8: [["تعمیر خودرو", "car-repair"], ["کارواش", "car-wash"], ["لاستیک و رینگ", "tires"], ["قطعات خودرو", "auto-parts"], ["کرایه خودرو", "car-rental"], ["باربری", "freight"], ["موتورسیکلت", "motorcycle"], ["باطری‌سازی", "battery"], ["نقاشی خودرو", "auto-paint"], ["آموزش رانندگی", "driving-school"]],
  c9: [["هتل", "hotel"], ["اقامتگاه بوم‌گردی", "eco-lodge"], ["آژانس مسافرتی", "travel-agency"], ["تور", "tour"], ["بلیط", "tickets"], ["راهنمای گردشگری", "tour-guide"], ["رزرو اقامت", "accommodation"], ["کمپینگ", "camping"]],
  c10: [["باشگاه بدنسازی", "gym"], ["سوارکاری", "equestrian"], ["فوتبال", "football"], ["یوگا", "yoga"], ["شنا", "swimming"], ["لوازم کوهنوردی", "mountaineering"], ["رزمی", "martial-arts"], ["تنیس", "tennis"], ["دوچرخه‌سواری", "cycling"], ["ورزش بانوان", "women-sport"]],
  c11: [["گالری", "gallery"], ["عکاسی", "photography"], ["سینما و تئاتر", "cinema-theater"], ["کتاب و نشر", "publishing"], ["صنایع‌دستی", "handicraft"], ["موسیقی", "music"], ["نقاشی", "painting"], ["مجسمه‌سازی", "sculpture"]],
  c12: [["تأسیسات", "installations"], ["برق‌کاری", "electrician"], ["لوله‌کشی", "plumbing"], ["نجاری", "carpentry"], ["تعمیرات لوازم", "appliance-repair"], ["قفل و کلید", "locksmith"], ["جوشکاری", "welding"], ["تعمیر کولر", "air-conditioning"], ["شیشه‌بری", "glasswork"]],
  c13: [["دیجیتال مارکتینگ", "digital-marketing"], ["مدیریت اینستاگرام", "instagram-management"], ["تولید محتوا", "content-production"], ["سئو", "seo"], ["برندسازی", "branding"], ["طراحی سایت", "web-design"], ["تبلیغات", "advertising"], ["مشاوره کسب‌وکار", "business-consulting"], ["ادمین شبکه‌های اجتماعی", "social-media-manager"], ["طراحی گرافیک", "graphic-design"], ["عکاسی تبلیغاتی", "commercial-photography"]],
  c14: [["فروشگاه موبایل", "mobile-store"], ["تعمیرات موبایل", "mobile-repair"], ["خدمات کامپیوتری", "computer-services"], ["نرم‌افزار", "software"], ["امنیت شبکه", "cybersecurity"], ["هوش مصنوعی", "ai"], ["فروشگاه لوازم جانبی", "accessories"], ["دوربین مداربسته", "cctv"], ["گیمینگ", "gaming"]],
  c15: [["حسابداری", "accounting"], ["حسابرسی", "audit"], ["بیمه", "insurance"], ["وام و اعتبار", "credit"], ["مشاوره مالی", "financial-advice"], ["صرافی", "exchange"], ["خدمات مالیاتی", "tax"], ["کارگزاری", "brokerage"]],
  c16: [["وکیل", "lawyer"], ["دفتر اسناد رسمی", "notary"], ["مشاوره حقوقی", "legal-consulting"], ["ثبت شرکت", "company-registration"], ["داوری", "arbitration"], ["مهاجرت", "immigration"], ["ثبت اختراع", "patent"], ["امور خانواده", "family-law"]],
  c17: [["مشاور املاک", "real-estate-agency"], ["معماری", "architecture"], ["ساخت‌وساز", "construction"], ["دکوراسیون", "renovation"], ["مصالح ساختمانی", "building-materials"], ["تأسیسات ساختمان", "building-installations"], ["اجاره ملک", "property-rental"], ["ارزیابی ملک", "property-valuation"]],
  c18: [["تشریفات", "ceremony"], ["تالار", "hall"], ["برگزاری نمایشگاه", "exhibition"], ["گل‌آرایی", "floristry"], ["موسیقی مراسم", "event-music"], ["عکاسی مراسم", "event-photography"], ["کیک و دسر مراسم", "event-cake"], ["اجاره تجهیزات", "event-rental"]],
  c19: [["مهدکودک", "kindergarten"], ["اسباب‌بازی", "toys"], ["مشاوره خانواده", "family-consulting"], ["لباس کودک", "kids-fashion"], ["کلاس کودک", "kids-class"], ["پرستاری کودک", "childcare"], ["سیسمونی", "baby-essentials"], ["خدمات مادر و کودک", "mother-baby"]],
  c20: [["کلینیک حیوانات", "vet"], ["پت‌شاپ", "pet-shop"], ["پانسیون حیوانات", "pet-boarding"], ["آرایش حیوانات", "pet-grooming"], ["غذای حیوانات", "pet-food"], ["آموزش حیوانات", "pet-training"], ["واکسیناسیون حیوانات", "pet-vaccine"], ["پرورش حیوانات", "pet-breeding"]],
  c21: [["نهال و گلخانه", "nursery"], ["ماشین‌آلات کشاورزی", "farm-machinery"], ["محصولات ارگانیک", "organic"], ["دام و طیور", "livestock"], ["خدمات باغبانی", "gardening"], ["زنبورداری", "beekeeping"], ["بذر و کود", "seeds-fertilizer"], ["فروش محصولات کشاورزی", "farm-products"]],
  c22: [["کارخانه", "factory"], ["قطعات صنعتی", "industrial-parts"], ["ماشین‌آلات", "machinery"], ["بسته‌بندی", "packaging"], ["مواد اولیه", "raw-materials"], ["تولید سفارشی", "custom-production"], ["تجهیزات ایمنی", "safety-equipment"], ["خدمات پیمانکاری", "industrial-contracting"]],
  c23: [["چاپخانه", "printing"], ["طراحی گرافیک", "graphic-design"], ["خبرگزاری", "news-agency"], ["استودیو", "studio"], ["تبلیغات محیطی", "outdoor-ads"], ["ترجمه", "translation"], ["تولید ویدئو", "video-production"], ["رسانه دیجیتال", "digital-media"]],
  c24: [["نظافت منزل", "home-cleaning"], ["قالیشویی", "carpet-cleaning"], ["اسباب‌کشی", "moving"], ["خدمات باغبانی", "home-gardening"], ["خدمات پرستاری", "home-care"], ["خدمات خشکشویی", "laundry"], ["مبارزه با آفات", "pest-control"], ["تعمیرات منزل", "home-maintenance"]],
};

export const seedSubcategories: Subcategory[] = Object.entries(categorySubcategories).flatMap(
  ([category_id, items], categoryIndex) =>
    items.map(([name, slug], itemIndex) => ({
      id: `s${categoryIndex + 1}-${itemIndex + 1}`,
      category_id,
      name,
      slug,
    })),
);

export const seedBusinesses: Business[] = [
  {
    id: "b1",
    name: "باشگاه سوارکاری آفتاب",
    city_id: "mashhad",
    category_id: "c10",
    subcategory_id: "s10-2",
    address: "مشهد، بلوار وکیل‌آباد",
    lat: 36.297,
    lng: 59.556,
    phone: "09150000000",
    instagram: "aftab_equestrian",
    telegram: "aftab_equestrian",
    bale: "aftab_equestrian",
    whatsapp: "989150000000",
    neshan: null,
    hours: "۸ تا ۲۰",
    price_tier: 2,
    is_supporter: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: "b2",
    name: "کافه نمور",
    city_id: "mashhad",
    category_id: "c1",
    subcategory_id: "s1-1",
    address: "مشهد، احمدآباد",
    lat: 36.303,
    lng: 59.588,
    phone: "05100000000",
    instagram: "namoor.cafe",
    telegram: "namoorcafe",
    bale: "namoorcafe",
    whatsapp: "985100000000",
    neshan: null,
    hours: "۹ تا ۲۳",
    price_tier: 1,
    is_supporter: false,
    status: "approved",
    created_at: new Date().toISOString(),
  },
];