-- P0 hardening: persisted neighborhood seed, richer anonymous analytics, and reports.

insert into public.neighborhoods (city_id, name, slug, center_lat, center_lng, active) values
  ('mashhad', 'احمدآباد', 'ahmadabad', 36.2975, 59.6042, true),
  ('mashhad', 'سجاد', 'sajjad', 36.3167, 59.5668, true),
  ('mashhad', 'فردوسی', 'ferdowsi', 36.3377, 59.5395, true),
  ('mashhad', 'هاشمیه', 'hashemieh', 36.2676, 59.5678, true),
  ('mashhad', 'وکیل‌آباد', 'vakilabad', 36.2891, 59.5224, true),
  ('mashhad', 'کوهسنگی', 'kowsar', 36.2783, 59.5745, true),
  ('mashhad', 'گلشهر', 'golshahr', 36.3543, 59.5302, true),
  ('mashhad', 'طرقبه', 'torqabeh', 36.3072, 59.3697, true),
  ('tehran', 'ونک', 'vanak', 35.7577, 51.4101, true),
  ('tehran', 'تجریش', 'tajrish', 35.8058, 51.4282, true),
  ('tehran', 'سعادت‌آباد', 'saadatabad', 35.7851, 51.3705, true),
  ('tehran', 'صادقیه', 'sadeghieh', 35.7187, 51.3372, true),
  ('tehran', 'اکباتان', 'ekbatan', 35.6993, 51.3047, true),
  ('isfahan', 'مرکز شهر', 'central', 32.6546, 51.6680, true),
  ('shiraz', 'مرکز شهر', 'central', 29.5918, 52.5837, true),
  ('tabriz', 'مرکز شهر', 'central', 38.0962, 46.2738, true),
  ('karaj', 'مرکز شهر', 'central', 35.8400, 50.9391, true)
on conflict (city_id, slug) do update set name = excluded.name, center_lat = excluded.center_lat, center_lng = excluded.center_lng, active = excluded.active;

alter table public.analytics_events add column if not exists query text, add column if not exists city text, add column if not exists neighborhood text;
alter table public.analytics_events drop constraint if exists analytics_events_event_name_check;
alter table public.analytics_events add constraint analytics_events_event_name_check check (event_name in ('search', 'view_business', 'click_call', 'click_whatsapp', 'click_directions', 'search_no_results', 'call', 'directions', 'profile_view', 'whatsapp', 'website'));
create index if not exists analytics_events_event_name_created_at_idx on public.analytics_events (event_name, created_at desc);

create table if not exists public.business_reports (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  reason text not null check (reason in ('wrong_phone', 'wrong_address', 'closed', 'wrong_category', 'other')),
  note text,
  status text not null default 'received' check (status in ('received', 'reviewed', 'resolved')),
  created_at timestamptz not null default now()
);
alter table public.business_reports enable row level security;
drop policy if exists "public insert business reports" on public.business_reports;
create policy "public insert business reports" on public.business_reports for insert to anon, authenticated with check (status = 'received');
drop policy if exists "admin read business reports" on public.business_reports;
create policy "admin read business reports" on public.business_reports for select to authenticated using (true);
drop policy if exists "admin update business reports" on public.business_reports;
create policy "admin update business reports" on public.business_reports for update to authenticated using (true);
create index if not exists business_reports_business_id_idx on public.business_reports (business_id);
