-- Neighborhood names from the user's supplied DOCX (30 cities, 300 entries).
-- The source says this is a shortlist, not an official/full municipal list. It also
-- contains streets, squares and other named areas. No center coordinates are guessed.
-- 11 names already exist in the earlier seed migration and keep their existing coordinates.

INSERT INTO public.cities (id, name, slug, active)
VALUES ('hamadan', 'همدان', 'hamadan', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, slug = EXCLUDED.slug, active = EXCLUDED.active;

INSERT INTO public.neighborhoods (city_id, name, slug, center_lat, center_lng, active)
VALUES
  ('tehran', 'شهرک غرب (دریا)', 'shhrk-ghrb-dria', null, null, true),
  ('tehran', 'پونک', 'ponk', null, null, true),
  ('tehran', 'نیاوران', 'niaoran', null, null, true),
  ('tehran', 'الهیه', 'alhih', null, null, true),
  ('tehran', 'زعفرانیه', 'zfranih', null, null, true),
  ('tehran', 'جردن', 'jrdn', null, null, true),
  ('tehran', 'یوسف‌آباد', 'iosf-abad', null, null, true),
  ('tehran', 'امیرآباد', 'amirabad', null, null, true),
  ('tehran', 'شهرآرا', 'shhrara', null, null, true),
  ('tehran', 'نارمک', 'narmk', null, null, true),
  ('tehran', 'تهرانپارس', 'thranpars', null, null, true),
  ('tehran', 'پاسداران', 'pasdaran', null, null, true),
  ('tehran', 'ولنجک', 'olnjk', null, null, true),
  ('tehran', 'قیطریه', 'qitrih', null, null, true),
  ('tehran', 'دروس', 'dros', null, null, true),
  ('tehran', 'فرمانیه', 'frmanih', null, null, true),
  ('tehran', 'شهران', 'shhran', null, null, true),
  ('tehran', 'آجودانیه', 'ajodanih', null, null, true),
  ('tehran', 'میرداماد', 'mirdamad', null, null, true),
  ('tehran', 'سهروردی', 'shrordi', null, null, true),
  ('tehran', 'جنت‌آباد', 'jnt-abad', null, null, true),
  ('tehran', 'هفت‌تیر', 'hft-tir', null, null, true),
  ('tehran', 'امیریه', 'amirih', null, null, true),
  ('tehran', 'حکیمیه', 'hkimih', null, null, true),
  ('tehran', 'نازی‌آباد', 'nazi-abad', null, null, true),
  ('tehran', 'خزانه', 'khzanh', null, null, true),
  ('tehran', 'هروی', 'hroi', null, null, true),
  ('tehran', 'مولوی', 'moloi', null, null, true),
  ('tehran', 'سنگلج', 'snglj', null, null, true),
  ('tehran', 'عودلاجان', 'odlajan', null, null, true),
  ('tehran', 'پامنار', 'pamnar', null, null, true),
  ('tehran', 'چیتگر', 'chitgr', null, null, true),
  ('tehran', 'یافت‌آباد', 'iaft-abad', null, null, true),
  ('tehran', 'ستارخان', 'starkhan', null, null, true),
  ('tehran', 'گیشا', 'gisha', null, null, true),
  ('tehran', 'تهران‌ویلا', 'thran-oila', null, null, true),
  ('tehran', 'شریف‌آباد', 'shrif-abad', null, null, true),
  ('mashhad', 'قاسم‌آباد', 'qasm-abad', null, null, true),
  ('mashhad', 'امامیه', 'amamih', null, null, true),
  ('mashhad', 'ثامن', 'samn', null, null, true),
  ('mashhad', 'رضاشهر', 'rzashhr', null, null, true),
  ('mashhad', 'پنج‌تن', 'pnj-tn', null, null, true),
  ('mashhad', 'گاز', 'gaz', null, null, true),
  ('mashhad', 'توس', 'tos', null, null, true),
  ('mashhad', 'الهیه', 'alhih', null, null, true),
  ('mashhad', 'سناباد', 'snabad', null, null, true),
  ('mashhad', 'بلوار معلم', 'bloar-mlm', null, null, true),
  ('mashhad', 'ملک‌آباد', 'mlk-abad', null, null, true),
  ('mashhad', 'طلاب', 'tlab', null, null, true),
  ('mashhad', 'فرهنگ', 'frhng', null, null, true),
  ('mashhad', 'چهارراه شهدا', 'chharrah-shhda', null, null, true),
  ('mashhad', 'نوفل‌لوشاتو', 'nofl-loshato', null, null, true),
  ('mashhad', 'مدرس', 'mdrs', null, null, true),
  ('isfahan', 'چهارباغ', 'chharbagh', null, null, true),
  ('isfahan', 'جلفا', 'jlfa', null, null, true),
  ('isfahan', 'جی', 'ji', null, null, true),
  ('isfahan', 'سپاهان‌شهر', 'spahan-shhr', null, null, true),
  ('isfahan', 'کاوه', 'kaoh', null, null, true),
  ('isfahan', 'احمدآباد', 'ahmdabad', null, null, true),
  ('isfahan', 'مرداویج', 'mrdaoij', null, null, true),
  ('isfahan', 'شهشهان', 'shhshhan', null, null, true),
  ('isfahan', 'بزرگمهر', 'bzrgmhr', null, null, true),
  ('isfahan', 'آتشگاه', 'atshgah', null, null, true),
  ('isfahan', 'دروازه شیراز', 'droazh-shiraz', null, null, true),
  ('isfahan', 'دردشت', 'drdsht', null, null, true),
  ('isfahan', 'رهنان', 'rhnan', null, null, true),
  ('isfahan', 'نظر', 'nzr', null, null, true),
  ('isfahan', 'تخت فولاد', 'tkht-folad', null, null, true),
  ('isfahan', 'دستگرد', 'dstgrd', null, null, true),
  ('isfahan', 'ملک‌شهر', 'mlk-shhr', null, null, true),
  ('isfahan', 'پل‌شهرستان', 'pl-shhrstan', null, null, true),
  ('isfahan', 'هزار جریب', 'hzar-jrib', null, null, true),
  ('karaj', 'گوهردشت', 'gohrdsht', null, null, true),
  ('karaj', 'مهرشهر', 'mhrshhr', null, null, true),
  ('karaj', 'عظیمیه', 'zimih', null, null, true),
  ('karaj', 'فردیس', 'frdis', null, null, true),
  ('karaj', 'کمال‌شهر', 'kmal-shhr', null, null, true),
  ('karaj', 'جهان‌شهر', 'jhan-shhr', null, null, true),
  ('karaj', 'حصارک', 'hsark', null, null, true),
  ('karaj', 'شاهین‌ویلا', 'shahin-oila', null, null, true),
  ('karaj', 'باغستان', 'baghstan', null, null, true),
  ('karaj', 'رجایی‌شهر', 'rjaii-shhr', null, null, true),
  ('karaj', 'مهردشت', 'mhrdsht', null, null, true),
  ('karaj', 'گلشهر', 'glshhr', null, null, true),
  ('karaj', 'مارلیک', 'marlik', null, null, true),
  ('karaj', 'سیمین‌دشت', 'simin-dsht', null, null, true),
  ('shiraz', 'معالی‌آباد', 'mali-abad', null, null, true),
  ('shiraz', 'قصردشت', 'qsrdsht', null, null, true),
  ('shiraz', 'زرگری', 'zrgri', null, null, true),
  ('shiraz', 'سعدی', 'sdi', null, null, true),
  ('shiraz', 'چمران', 'chmran', null, null, true),
  ('shiraz', 'ملاصدرا', 'mlasdra', null, null, true),
  ('shiraz', 'گلدشت', 'gldsht', null, null, true),
  ('shiraz', 'ستارخان', 'starkhan', null, null, true),
  ('shiraz', 'فرهنگ‌شهر', 'frhng-shhr', null, null, true),
  ('shiraz', 'بوستان', 'bostan', null, null, true),
  ('shiraz', 'قدوسی', 'qdosi', null, null, true),
  ('shiraz', 'باغ‌تخت', 'bagh-tkht', null, null, true),
  ('shiraz', 'شهرک گلستان', 'shhrk-glstan', null, null, true),
  ('shiraz', 'میدان ارم', 'midan-arm', null, null, true),
  ('tabriz', 'ولیعصر', 'olisr', null, null, true),
  ('tabriz', 'ائل‌گلی', 'ael-gli', null, null, true),
  ('tabriz', 'ولیامر', 'oliamr', null, null, true),
  ('tabriz', 'رشدیه', 'rshdih', null, null, true),
  ('tabriz', 'باغمیشه', 'baghmishh', null, null, true),
  ('tabriz', 'آبرسان', 'abrsan', null, null, true),
  ('tabriz', 'عباسی', 'basi', null, null, true),
  ('tabriz', 'یاغچیان', 'iaghchian', null, null, true),
  ('tabriz', 'آخماقیه', 'akhmaqih', null, null, true),
  ('tabriz', 'ششگلان', 'shshglan', null, null, true),
  ('tabriz', 'منظریه', 'mnzrih', null, null, true),
  ('tabriz', 'مارالان', 'maralan', null, null, true),
  ('tabriz', 'شریعتی', 'shriti', null, null, true),
  ('qom', 'صفاییه', 'sfaiih', null, null, true),
  ('qom', 'پردیسان', 'prdisan', null, null, true),
  ('qom', 'نیروگاه', 'nirogah', null, null, true),
  ('qom', 'زنبیل‌آباد', 'znbil-abad', null, null, true),
  ('qom', 'انصاریان', 'ansarian', null, null, true),
  ('qom', 'ایستگاه', 'aistgah', null, null, true),
  ('qom', 'چهارمردان', 'chharmrdan', null, null, true),
  ('qom', 'شاهزاده ابراهیم', 'shahzadh-abrahim', null, null, true),
  ('qom', 'توحید', 'tohid', null, null, true),
  ('qom', 'سالاریه', 'salarih', null, null, true),
  ('qom', 'شهرک قدس', 'shhrk-qds', null, null, true),
  ('qom', 'پیامبر اعظم', 'piambr-azm', null, null, true),
  ('ahvaz', 'کیانپارس', 'kianpars', null, null, true),
  ('ahvaz', 'کیان‌آباد', 'kian-abad', null, null, true),
  ('ahvaz', 'زیتون کارمندی', 'ziton-karmndi', null, null, true),
  ('ahvaz', 'گلستان', 'glstan', null, null, true),
  ('ahvaz', 'ملی‌راه', 'mli-rah', null, null, true),
  ('ahvaz', 'کوروش', 'korosh', null, null, true),
  ('ahvaz', 'امانیه', 'amanih', null, null, true),
  ('ahvaz', 'لشگرآباد', 'lshgrabad', null, null, true),
  ('ahvaz', 'سیاحی', 'siahi', null, null, true),
  ('ahvaz', 'چهار شیر', 'chhar-shir', null, null, true),
  ('ahvaz', 'نادری', 'nadri', null, null, true),
  ('ahvaz', 'عامری', 'amri', null, null, true),
  ('ahvaz', 'حصیرآباد', 'hsirabad', null, null, true),
  ('ahvaz', 'ناصری', 'nasri', null, null, true),
  ('ahvaz', 'شهرک نفت', 'shhrk-nft', null, null, true),
  ('kermanshah', 'طاق‌بستان', 'taq-bstan', null, null, true),
  ('kermanshah', 'کوی نواب', 'koi-noab', null, null, true),
  ('kermanshah', 'دولت‌آباد', 'dolt-abad', null, null, true),
  ('kermanshah', 'کوی ولیعصر', 'koi-olisr', null, null, true),
  ('kermanshah', 'کیانشهر', 'kianshhr', null, null, true),
  ('kermanshah', 'باغ ابریشم', 'bagh-abrishm', null, null, true),
  ('kermanshah', 'شاطرآباد', 'shatrabad', null, null, true),
  ('kermanshah', 'فرهنگیان', 'frhngian', null, null, true),
  ('kermanshah', 'میدان آزادی', 'midan-azadi', null, null, true),
  ('kermanshah', 'بلوار شهید بهشتی', 'bloar-shhid-bhshti', null, null, true),
  ('urmia', 'نازلو', 'nazlo', null, null, true),
  ('urmia', 'شهرک ولیعصر', 'shhrk-olisr', null, null, true),
  ('urmia', 'فرهنگیان', 'frhngian', null, null, true),
  ('urmia', 'سیلو', 'silo', null, null, true),
  ('urmia', 'خیابان مدنی', 'khiaban-mdni', null, null, true),
  ('urmia', 'شهرک انقلاب', 'shhrk-anqlab', null, null, true),
  ('rasht', 'گلسار', 'glsar', null, null, true),
  ('rasht', 'منظریه', 'mnzrih', null, null, true),
  ('rasht', 'سبزه‌میدان', 'sbzh-midan', null, null, true),
  ('rasht', 'لاکان', 'lakan', null, null, true),
  ('rasht', 'ساغریسازان', 'saghrisazan', null, null, true),
  ('rasht', 'بلوار انصاری', 'bloar-ansari', null, null, true),
  ('rasht', 'خیابان معلم', 'khiaban-mlm', null, null, true),
  ('rasht', 'میدان شهرداری', 'midan-shhrdari', null, null, true),
  ('rasht', 'ریل‌سازی', 'ril-sazi', null, null, true),
  ('rasht', 'کوچ‌صفهان', 'koch-sfhan', null, null, true),
  ('zahedan', 'خیابان سعدی', 'khiaban-sdi', null, null, true),
  ('zahedan', 'خیابان دانشگاه', 'khiaban-danshgah', null, null, true),
  ('zahedan', 'شهرک امام خمینی', 'shhrk-amam-khmini', null, null, true),
  ('zahedan', 'شهرک مهدیه', 'shhrk-mhdih', null, null, true),
  ('zahedan', 'کوی مهرگان', 'koi-mhrgan', null, null, true),
  ('zahedan', 'خیابان خلیج فارس', 'khiaban-khlij-fars', null, null, true),
  ('kerman', 'شهرک شهید چمران', 'shhrk-shhid-chmran', null, null, true),
  ('kerman', 'شهرک صنعتی', 'shhrk-snti', null, null, true),
  ('kerman', 'خیابان شریعتی', 'khiaban-shriti', null, null, true),
  ('kerman', 'ماهان', 'mahan', null, null, true),
  ('kerman', 'کوی کشاورز', 'koi-kshaorz', null, null, true),
  ('kerman', 'بلوار جمهوری', 'bloar-jmhori', null, null, true),
  ('kerman', 'میدان آزادی', 'midan-azadi', null, null, true),
  ('kerman', 'خیابان مطهری', 'khiaban-mthri', null, null, true),
  ('kerman', 'گلدشت', 'gldsht', null, null, true),
  ('hamedan', 'میدان امام', 'midan-amam', null, null, true),
  ('hamedan', 'خیابان باباطاهر', 'khiaban-babatahr', null, null, true),
  ('hamedan', 'شهرک مدنی', 'shhrk-mdni', null, null, true),
  ('hamedan', 'شهرک مهدیه', 'shhrk-mhdih', null, null, true),
  ('hamedan', 'بلوار آیت‌الله مدنی', 'bloar-ait-allh-mdni', null, null, true),
  ('hamedan', 'خیابان شریعتی', 'khiaban-shriti', null, null, true),
  ('hamedan', 'گنجنامه', 'gnjnamh', null, null, true),
  ('hamedan', 'خیابان بوعلی', 'khiaban-boli', null, null, true),
  ('hamedan', 'میدان ۱۳ آبان', 'midan-13-aban', null, null, true),
  ('yazd', 'فهادان', 'fhadan', null, null, true),
  ('yazd', 'دروازه قرآن', 'droazh-qran', null, null, true),
  ('yazd', 'شاهدی', 'shahdi', null, null, true),
  ('yazd', 'میدان امیرچخماق', 'midan-amirchkhmaq', null, null, true),
  ('yazd', 'صفائیه', 'sfaeih', null, null, true),
  ('yazd', 'شهرک امام حسین', 'shhrk-amam-hsin', null, null, true),
  ('yazd', 'بلوار جمهوری', 'bloar-jmhori', null, null, true),
  ('yazd', 'خیابان کاشانی', 'khiaban-kashani', null, null, true),
  ('yazd', 'شهرک مصلی', 'shhrk-msli', null, null, true),
  ('yazd', 'کوی ولیعصر', 'koi-olisr', null, null, true),
  ('ardabil', 'خیابان ارشاد', 'khiaban-arshad', null, null, true),
  ('ardabil', 'خیابان امام', 'khiaban-amam', null, null, true),
  ('ardabil', 'شهرک خلیل‌آباد', 'shhrk-khlil-abad', null, null, true),
  ('ardabil', 'بلوار دانشگاه', 'bloar-danshgah', null, null, true),
  ('ardabil', 'خیابان جمهوری', 'khiaban-jmhori', null, null, true),
  ('ardabil', 'میدان بسیج', 'midan-bsij', null, null, true),
  ('ardabil', 'کوی ولیعصر', 'koi-olisr', null, null, true),
  ('bandar-abbas', 'شهرک نگین', 'shhrk-ngin', null, null, true),
  ('bandar-abbas', 'میدان امام حسین', 'midan-amam-hsin', null, null, true),
  ('bandar-abbas', 'خیابان شهید چمران', 'khiaban-shhid-chmran', null, null, true),
  ('bandar-abbas', 'شهرک خلیج فارس', 'shhrk-khlij-fars', null, null, true),
  ('bandar-abbas', 'کوی ولیعصر', 'koi-olisr', null, null, true),
  ('bandar-abbas', 'میدان شهدا', 'midan-shhda', null, null, true),
  ('bandar-abbas', 'سورو', 'soro', null, null, true),
  ('arak', 'خیابان شریعتی', 'khiaban-shriti', null, null, true),
  ('arak', 'شهرک امام خمینی', 'shhrk-amam-khmini', null, null, true),
  ('arak', 'بلوار شهید بهشتی', 'bloar-shhid-bhshti', null, null, true),
  ('arak', 'خیابان مدرس', 'khiaban-mdrs', null, null, true),
  ('arak', 'میدان امام', 'midan-amam', null, null, true),
  ('arak', 'شهرک قدس', 'shhrk-qds', null, null, true),
  ('arak', 'خیابان سردار جنگل', 'khiaban-srdar-jngl', null, null, true),
  ('zanjan', 'خیابان امام', 'khiaban-amam', null, null, true),
  ('zanjan', 'شهرک ولیعصر', 'shhrk-olisr', null, null, true),
  ('zanjan', 'میدان ولیعصر', 'midan-olisr', null, null, true),
  ('zanjan', 'خیابان شهید بهشتی', 'khiaban-shhid-bhshti', null, null, true),
  ('zanjan', 'شهرک مهدیه', 'shhrk-mhdih', null, null, true),
  ('zanjan', 'کوی ارم', 'koi-arm', null, null, true),
  ('sanandaj', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('sanandaj', 'خیابان پاسداران', 'khiaban-pasdaran', null, null, true),
  ('sanandaj', 'بلوار کردستان', 'bloar-krdstan', null, null, true),
  ('sanandaj', 'خیابان ۱۷ شهریور', 'khiaban-17-shhrior', null, null, true),
  ('sanandaj', 'شهرک ولیعصر', 'shhrk-olisr', null, null, true),
  ('sanandaj', 'بلوار بهار', 'bloar-bhar', null, null, true),
  ('qazvin', 'شهرک عصر انقلاب', 'shhrk-sr-anqlab', null, null, true),
  ('qazvin', 'بلوار شهید بهشتی', 'bloar-shhid-bhshti', null, null, true),
  ('qazvin', 'خیابان مولوی', 'khiaban-moloi', null, null, true),
  ('qazvin', 'میدان آزادی', 'midan-azadi', null, null, true),
  ('qazvin', 'شهرک مهدیه', 'shhrk-mhdih', null, null, true),
  ('qazvin', 'خیابان انقلاب', 'khiaban-anqlab', null, null, true),
  ('khorramabad', 'خیابان شریعتی', 'khiaban-shriti', null, null, true),
  ('khorramabad', 'شهرک ولیعصر', 'shhrk-olisr', null, null, true),
  ('khorramabad', 'بلوار مدرس', 'bloar-mdrs', null, null, true),
  ('khorramabad', 'شهرک انقلاب', 'shhrk-anqlab', null, null, true),
  ('khorramabad', 'کوی رازی', 'koi-razi', null, null, true),
  ('khorramabad', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('gorgan', 'خیابان ولیعصر', 'khiaban-olisr', null, null, true),
  ('gorgan', 'شهرک نبوت', 'shhrk-nbot', null, null, true),
  ('gorgan', 'بلوار شهید بهشتی', 'bloar-shhid-bhshti', null, null, true),
  ('gorgan', 'شهرک هلال احمر', 'shhrk-hlal-ahmr', null, null, true),
  ('gorgan', 'خیابان شریعتی', 'khiaban-shriti', null, null, true),
  ('gorgan', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('sari', 'خیابان فرهنگ', 'khiaban-frhng', null, null, true),
  ('sari', 'شهرک امام خمینی', 'shhrk-amam-khmini', null, null, true),
  ('sari', 'خیابان طالب آملی', 'khiaban-talb-amli', null, null, true),
  ('sari', 'میدان امام', 'midan-amam', null, null, true),
  ('sari', 'بلوار خزر', 'bloar-khzr', null, null, true),
  ('sari', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('bushehr', 'شهرک کوثر', 'shhrk-kosr', null, null, true),
  ('bushehr', 'کوی ولیعصر', 'koi-olisr', null, null, true),
  ('bushehr', 'خیابان امام', 'khiaban-amam', null, null, true),
  ('bushehr', 'میدان ولیعصر', 'midan-olisr', null, null, true),
  ('bushehr', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('bushehr', 'بلوار ساحلی', 'bloar-sahli', null, null, true),
  ('birjand', 'خیابان معلم', 'khiaban-mlm', null, null, true),
  ('birjand', 'شهرک ولیعصر', 'shhrk-olisr', null, null, true),
  ('birjand', 'بلوار غفاری', 'bloar-ghfari', null, null, true),
  ('birjand', 'میدان مصلی', 'midan-msli', null, null, true),
  ('birjand', 'خیابان مدرس', 'khiaban-mdrs', null, null, true),
  ('birjand', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('ilam', 'شهرک امام خمینی', 'shhrk-amam-khmini', null, null, true),
  ('ilam', 'بلوار شهید بهشتی', 'bloar-shhid-bhshti', null, null, true),
  ('ilam', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('ilam', 'خیابان ولیعصر', 'khiaban-olisr', null, null, true),
  ('ilam', 'کوی ولیعصر', 'koi-olisr', null, null, true),
  ('shahrekord', 'خیابان امام', 'khiaban-amam', null, null, true),
  ('shahrekord', 'شهرک ولیعصر', 'shhrk-olisr', null, null, true),
  ('shahrekord', 'بلوار مدرس', 'bloar-mdrs', null, null, true),
  ('shahrekord', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('shahrekord', 'میدان آزادی', 'midan-azadi', null, null, true),
  ('yasuj', 'بلوار شهید بهشتی', 'bloar-shhid-bhshti', null, null, true),
  ('yasuj', 'خیابان امام', 'khiaban-amam', null, null, true),
  ('yasuj', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('yasuj', 'خیابان شریعتی', 'khiaban-shriti', null, null, true),
  ('yasuj', 'شهرک ولیعصر', 'shhrk-olisr', null, null, true),
  ('semnan', 'خیابان امام', 'khiaban-amam', null, null, true),
  ('semnan', 'بلوار ولیعصر', 'bloar-olisr', null, null, true),
  ('semnan', 'شهرک فرهنگیان', 'shhrk-frhngian', null, null, true),
  ('semnan', 'خیابان مدرس', 'khiaban-mdrs', null, null, true),
  ('semnan', 'شهرک امام خمینی', 'shhrk-amam-khmini', null, null, true)
ON CONFLICT (city_id, slug) DO UPDATE SET name = EXCLUDED.name, active = EXCLUDED.active;
