-- Phase P0: local discovery primitives.
create table if not exists public.neighborhoods (
  id uuid primary key default gen_random_uuid(),
  city_id text not null references public.cities(id) on delete cascade,
  name text not null,
  slug text not null,
  center_lat double precision,
  center_lng double precision,
  active boolean not null default true,
  unique(city_id, slug)
);

alter table public.businesses add column if not exists neighborhood_slug text;
alter table public.businesses add column if not exists search_terms text[] not null default '{}';
alter table public.businesses add column if not exists is_verified boolean not null default false;

create index if not exists neighborhoods_city_id_idx on public.neighborhoods(city_id);
create index if not exists businesses_search_terms_gin_idx on public.businesses using gin(search_terms);
create index if not exists businesses_neighborhood_slug_idx on public.businesses(neighborhood_slug);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('call','directions','profile_view','whatsapp','website')),
  business_id uuid references public.businesses(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.neighborhoods enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "public read active neighborhoods" on public.neighborhoods;
create policy "public read active neighborhoods" on public.neighborhoods for select to anon, authenticated using (active = true);
drop policy if exists "public insert analytics events" on public.analytics_events;
create policy "public insert analytics events" on public.analytics_events for insert to anon, authenticated with check (true);
drop policy if exists "admin read analytics events" on public.analytics_events;
create policy "admin read analytics events" on public.analytics_events for select to authenticated using (true);
